### ISSUE TITLE
Wrong source path in dub package

### ISSUE THREAD

**Issue by prasunanand** [dataPulverizer/gsl#1]
I was unable to import modules.

In `.dub/packages/gsl-0.1.7/dub.json` I found that the import path is wrong as
```
"importPaths": [
		"source/"
	]
```

I corrected this by modifying the importPaths to
```
"importPaths": [
		"source/headers/"
	]
```

**Comment by dataPulverizer** [comment]
Sorry about that, I am changing the package right now :-)

**Comment by dataPulverizer** [comment]
p.s. I was working on another package, I thought you were talking about a different one I don't think dstats uses this one as a dependency, I have just checked the dstats dub file and gsl is not there. I think you may have commented on the wrong repository

**Comment by dataPulverizer** [comment]
I updated this package yesterday because I realised that it was not compiling from dub because of the changes to the folder structure requirements in DUB. I changed the folder structure so that a user can include gsl as a dependency in their package and import it easily.

**Comment by prasunanand** [comment]
@dataPulverizer . Sorry, I was referring to gsl. I have edited my initial comment :) .

**Comment by prasunanand** [comment]
Ah! There were two gsl packages 0.1.0 and 0.1.7. There was somehow an error. 
I deleted gsl-0.1.0
Now, everything is working fine ;) .
~A dlang-newbie.
